### ISSUE TITLE
unable to add a job on a project

### ISSUE THREAD

**Issue by vanadar** [jbox-web/redmine_jenkins#18]
hi,

when i configure The Jenkins' plugin and want to add a job, i have an error 500.

here are the logs:

```
Processing by JenkinsJobsController#new as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
  Rendered plugins/redmine_jenkins/app/views/jenkins_jobs/new.html.erb within layouts/base (4.9ms)
Completed 500 Internal Server Error in 119.5ms

ActionView::Template::Error (undefined method `builds_to_keep' for #<JenkinsJob:0x00000006e405b0>):
    17:   </p>
    18: 
    19:   <p>
    20:     <%= f.text_field :builds_to_keep %>
    21:   </p>
    22: 
    23:   <% if !@is_xhr %>
  lib/redmine/views/labelled_form_builder.rb:31:in `text_field'
  app/helpers/application_helper.rb:1043:in `labelled_form_for'
```

**Comment by vanadar** [comment]
it might have been a bug with the cache. it is working now
