### ISSUE TITLE
500 in Project welcome page after enabling plugin

### ISSUE THREAD

**Issue by gionn** [jbox-web/redmine_jenkins#20]
I think this is some conflict between gems used by redmine_git_hosting plugin and redmine_jenkins, but I am not enough into rails to debug.

Redmine 2.4.2

```
Started GET "/projects/cloudesire" for 87.3.203.204 at 2014-10-30 06:50:22 +0000
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"cloudesire"}
  Current user: g.toraldo (id=5)
  Rendered plugins/redmine_git_hosting/app/views/common/_git_urls.html.erb (11.3ms)
  Rendered plugins/redmine_git_hosting/app/views/projects/_git_urls.html.erb (17.5ms)
  Rendered projects/show.html.erb within layouts/base (31.7ms)
Completed 500 Internal Server Error in 169.8ms

ActionView::Template::Error (wrong number of arguments (1 for 2)):
    41: 
    42:     $(document).ready(function() {
    43:       var git_url_client = Object();
    44:       git_url_client.movie_path    = '<%= plugin_asset_link('ZeroClipboard.swf') %>';
    45:       git_url_client.label_to_copy = '<%= l(:label_copy_to_clipboard) %>';
    46:       git_url_client.label_copied  = '<%= l(:label_copied_to_clipboard) %>';
    47:       git_url_client.target        = '#clipboard_button';
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/projects/show.html.erb:63:in `_app_views_projects_show_html_erb___4005629072884248950_58066900'
  app/controllers/projects_controller.rb:163:in `show'
```

**Comment by n-rodriguez** [comment]
Update both plugins ;) (devel branch for this one and 0.7.8 or 0.8 for Redmine Git Hosting)
