### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by salehi** [jbox-web/redmine_jenkins#25]
Hello, 

When I try to migrate plugins through executing rake, I deal with : "rake aborted!" error.
Note that I executed successfully the "bundle install" before this time for this plugin.

```
redmine@dev:/opt/redmine/current/plugins/redmine_jenkins$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/redmine/current)
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x0000000216ed90>
/var/lib/gems/1.9.1/gems/railties-4.1.8/lib/rails/railtie/configuration.rb:96:in `method_missing'
/opt/redmine/current/config/application.rb:25:in `<class:Application>'
/opt/redmine/current/config/application.rb:13:in `<module:RedmineApp>'
/opt/redmine/current/config/application.rb:12:in `<top (required)>'
/opt/redmine/current/Rakefile:5:in `require'
/opt/redmine/current/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
redmine@dev:/opt/redmine/current/plugins/redmine_jenkins$ 
```

**Comment by n-rodriguez** [comment]
Your must run the Rake task in Redmine root dir : http://www.redmine.org/projects/redmine/wiki/Plugins

**Comment by salehi** [comment]
No No, 
This is due to rails version since redmine 2.6 uses another version of rails and redmine_jenkins plugins do NOT compatible with that version. It is the correct answer exactly.
