### ISSUE TITLE
Missing helper file helpers/bootstrap_switch_helper.rb

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_jenkins#30]
Using latest git here and bootstrap_kit v0.2.1

```
rake aborted!
LoadError: Missing helper file helpers/bootstrap_switch_helper.rb
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:13:in `block in included'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `class_eval'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `included'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:39:in `include'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:39:in `<top (required)>'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:11:in `block (2 levels) in <top (required)>'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `each'
/var/lib/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `block in <top (required)>'
/var/lib/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by n-rodriguez** [comment]
You can temporary use the v0.2x branch of bootstrap_kit.
