### ISSUE TITLE
Migration failed - SQLite3::SQLException: table "jenkins_settings" already exists

### ISSUE THREAD

**Issue by mrueg** [jbox-web/redmine_jenkins#33]
Hi,

I've been trying to upgrade to 1.0.0 and the sql migration seems to fail. Any idea how I can fix this?

```
==  CreateJenkinsSettings: migrating ==========================================
-- create_table(:jenkins_settings)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "jenkins_settings" already exists: CREATE TABLE "jenkins_settings" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "project_id" integer, "url" varchar(255), "auth_user" varchar(255) DEFAULT '', "auth_password" varchar(255) DEFAULT '', "show_compact" boolean DEFAULT 'f', "get_build_details" boolean DEFAULT 't', "wait_for_build_id" boolean DEFAULT 'f') /var/lib/redmine/plugins/redmine_jenkins/db/migrate/20150316023100_create_jenkins_settings.rb:4:in `change'
/var/lib/redmine/lib/redmine/plugin.rb:469:in `migrate_plugin'
/var/lib/redmine/lib/redmine/plugin.rb:441:in `migrate'
/var/lib/redmine/lib/redmine/plugin.rb:455:in `block in migrate'
/var/lib/redmine/lib/redmine/plugin.rb:454:in `each'
/var/lib/redmine/lib/redmine/plugin.rb:454:in `migrate'
/var/lib/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
```

**Comment by n-rodriguez** [comment]
> I've been trying to upgrade to 1.0.0 and the sql migration seems to fail. Any idea how I can fix this?

Hi! I'm sorry but you cannot migrate to 1.0.0. You need to do a clean install.

**Comment by mrueg** [comment]
Okay, thank you. That worked!
