### ISSUE TITLE
LoadError: Missing helper file helpers/redmine_bootstrap_kit_helper.rb

### ISSUE THREAD

**Issue by webfractor** [jbox-web/redmine_jenkins#36]
Installed redmine on CentOS7 as follows:

```
yum install @development mariadb-server mariadb-devel ruby ruby-devel ImageMagick ImageMagick-devel rubygem-rake rubygem-bundler
 sudo systemctl enable mariadb
 sudo systemctl start mariadb
 sudo mysql_secure_installation
mysql -u root -p
CREATE DATABASE redmine CHARACTER SET utf8;
CREATE USER 'redmine'@'localhost' IDENTIFIED BY 'mypassword';
GRANT ALL PRIVILEGES ON redmine.* TO 'redmine'@'localhost';
exit
sudo adduser redmine
curl -O http://www.redmine.org/releases/redmine-2.6.3.tar.gz
tar xvf redmine-2.6.3.tar.gz
sudo mv redmine-2.6.3/ /home/redmine/redmine
sudo chown -R redmine:redmine /home/redmine/redmine
sudo su redmine
cd ~/redmine
cp config/database.yml.example config/database.yml
vim config/database.yml #set user & pass for production
bundle install --without development test
rake generate_secret_token
RAILS_ENV=production rake db:migrate
RAILS_ENV=production rake redmine:load_default_data [optional]
mkdir -p tmp tmp/pdf public/plugin_assets
chown -R redmine:redmine files log tmp public/plugin_assets
chmod -R 755 files log tmp public/plugin_assets
ruby script/rails server webrick -e production
```

I was able to login with default admin password. @ myhost:3000

So, moved on to installing your redmine_jenkins plugin per the updated install docs @
https://github.com/jbox-web/redmine_jenkins/wiki/Step-by-step-installation-instructions

```
sudo su redmine
cd ~/redmine/plugins
git clone https://github.com/jbox-web/redmine_bootstrap_kit.git
cd redmine_bootstrap_kit/
git checkout 0.2.3
```

got the following error

```
error: pathspec '0.2.3' did not match any file(s) known to git.
```

Checked the git repo and you only have tags/releases up to 0.2.2, so I tried

```
git checkout 0.2.2
```

Seemed to work, continued

```
cd REDMINE_ROOT/plugins
git clone https://github.com/jbox-web/redmine_jenkins.git
cd redmine_jenkins/
git checkout 1.0.0
cd REDMINE_ROOT/
bundle install --without development test
```

no issues up to here

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine
```

and then i got the error in the issue name, full output:

```
rake aborted!
LoadError: Missing helper file helpers/redmine_bootstrap_kit_helper.rb
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:317:in `rescue in depend_on'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:312:in `depend_on'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:225:in `require_dependency'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/abstract_controller/helpers.rb:135:in `block in modules_for_helpers'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/abstract_controller/helpers.rb:131:in `map!'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/abstract_controller/helpers.rb:131:in `modules_for_helpers'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/action_controller/metal/helpers.rb:92:in `modules_for_helpers'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/abstract_controller/helpers.rb:95:in `helper'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:13:in `block in included'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `class_eval'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `included'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `include'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `<top (required)>'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:313:in `depend_on'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:225:in `require_dependency'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:11:in `block (2 levels) in <top (required)>'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `each'
/home/redmine/redmine/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `block in <top (required)>'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:429:in `_run__3212290410998519312__prepare__253601540202930503__callbacks'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/redmine/.gem/ruby/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/redmine/.gem/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/home/redmine/.gem/ruby/gems/railties-3.2.21/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by n-rodriguez** [comment]
Yeah. It's my fault... It depends on a not yet released lib version... I know it's bad :/

**Comment by n-rodriguez** [comment]
But don't worry it's a matter of days :) If you want to try you can checkout the devel branch.

**Comment by webfractor** [comment]
excellent, that worked like a charm.

This was much easier than the bitnami fiasco, once I figured out how to get redmine on centos7 from tarballs.

**Comment by n-rodriguez** [comment]
> excellent, that worked like a charm.

Great :)

> This was much easier than the bitnami fiasco, once I figured out how to get redmine on centos7 from tarballs.

The first time is always hard ^^

**Comment by webfractor** [comment]
I may spoken too soo. I create a test project with jenkins support. and when I try to go to the project settings I get an error

```
Started GET "/projects/test/settings" for 10.101.120.30 at 2015-03-30 16:45:21 -0500
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"test"}
  Current user: devadm (id=1)
  Rendered projects/_form.html.erb (11.2ms)
  Rendered projects/_edit.html.erb (12.7ms)
  Rendered projects/settings/_modules.html.erb (3.6ms)
  Rendered projects/settings/_members.html.erb (10.0ms)
  Rendered projects/settings/_versions.html.erb (2.8ms)
  Rendered projects/settings/_issue_categories.html.erb (1.1ms)
  Rendered projects/settings/_wiki.html.erb (1.5ms)
  Rendered projects/settings/_repositories.html.erb (1.1ms)
  Rendered projects/settings/_boards.html.erb (1.1ms)
  Rendered projects/settings/_activities.html.erb (6.2ms)
  Rendered plugins/redmine_jenkins/app/views/common/_jenkins_js_headers.html.haml (120.1ms)
  Rendered plugins/redmine_jenkins/app/views/projects/settings/_redmine_jenkins.html.haml (120.5ms)
  Rendered common/_tabs.html.erb (165.6ms)
  Rendered projects/settings.html.erb within layouts/base (166.6ms)
Completed 500 Internal Server Error in 249.6ms

ActionView::Template::Error (undefined method `redmine_bootstrap_kit_load' for #<#<Class:0x00000006dc8e70>:0x00000006fc52a0>):
    1: - content_for :header_tags do
    2:   = redmine_bootstrap_kit_load(:redmine_bootstrap_kit)
    3:   = redmine_bootstrap_kit_load(:bootstrap_label)
    4:   = redmine_bootstrap_kit_load(:bootstrap_modals)
    5:   = redmine_bootstrap_kit_load(:bootstrap_pagination)
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___1273639142757581603_26851300'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___1273639142757581603_26851300'
  app/helpers/application_helper.rb:328:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___4496887609699569314_26779460'
```

**Comment by n-rodriguez** [comment]
Yes... Actually I was expecting this kind of bugs...

**Comment by webfractor** [comment]
I only set the bootstrap_kit to devel, should I set both plugins to devel?

**Comment by n-rodriguez** [comment]
Nope.. I think I need to update Jenkins before... I'm checking it

**Comment by webfractor** [comment]
kk, I'm off work, I'll check back later tonight from home if I get the chance, otherwise I'll check tomorrow.

Thanks for you rapid responses.

**Comment by webfractor** [comment]
I'd be willing to bet that at this point, I'm having the same issues as issue #35.

**Comment by webfractor** [comment]
should I update something, or did you close this in favor of issue #35?

**Comment by n-rodriguez** [comment]
> did you close this in favor of issue #35?

Yes :)
