### ISSUE TITLE
Fail to install on Redmine 3.0.1

### ISSUE THREAD

**Issue by abatista75** [jbox-web/redmine_jenkins#37]
Here is the log

```
(in /usr/share/redmine-3.0.1)
rake aborted!
Missing helper file helpers/redmine_bootstrap_kit_helper.rb
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:144:in `map!'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/abstract_controller/helpers.rb:108:in `helper'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:13:in `block in included'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `class_eval'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `included'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `include'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in `require_dependency'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins.rb:11:in `block (2 levels) in <top (required)>'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `each'
/usr/share/redmine-3.0.1/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine-3.0.1/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by jbanyai** [comment]
Hi!

I get exactly the same error log. 

Windows server, Redmine 3.0.1

**Comment by n-rodriguez** [comment]
Have you installed Redmine Bootstrap Kit?

**Comment by abatista75** [comment]
You are totally right... I missed to reinstalled Redmine Bootstrap Kit (I did it, but I uninstalled later on and I forgot to reinstall it)
