### ISSUE TITLE
Error when sorting issues using custom fields

### ISSUE THREAD

**Issue by zshahan** [jbox-web/redmine_jenkins#39]
After adding this plugin, I get a 500 error when attempting to sort issues via custom fields.

```
Started GET "/projects/fdlic/issues" for 127.0.0.1 at 2015-04-24 11:26:08 -0500
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"fdlic"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 425ms (ActiveRecord: 20.2ms)

ArgumentError (wrong number of arguments (0 for 1..2)):
  app/models/issue_query.rb:343:in 'issues'
  app/controllers/issues_controller.rb:70:in 'index'

Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            2.3.3
  Filesystem
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_jenkins                1.0.1
```

**Comment by shawndibble** [comment]
I am also experiencing the same issue/error. Here are my environment settings:

Environment:
  Redmine version                3.0.3.stable.14325
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               Mysql2

**Comment by wilsoc5** [comment]
I can verify this. We had this plugin installed and then needed to start using some custom fields. Tried to sort the issues with the new custom fields and would get an internal error (the same ArgumentError as above). Removed this plugin and no issue in sorting.
