### ISSUE TITLE
error 500 caused by invalid sql on user page

### ISSUE THREAD

**Issue by Guite** [jbox-web/redmine_jenkins#4]
A 500 status code is thrown when opening a user's account page, like for example https://your-redmine-install.org/users/123
The log file contains the following error:

```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'jenkins_builds.author_id' in 'where clause': SELECT  `jenkins_builds`.`id` AS t0_r0, `jenkins_builds`.`jenkins_job_id` AS t0_r1, `jenkins_builds`.`number` AS t0_r2, `jenkins_builds`.`result` AS t0_r3, `jenkins_builds`.`finished_at` AS t0_r4, `jenkins_builds`.`building` AS t0_r5, `jenkins_builds`.`duration` AS t0_r6, `jenkins_jobs`.`id` AS t1_r0, `jenkins_jobs`.`project_id` AS t1_r1, `jenkins_jobs`.`repository_id` AS t1_r2, `jenkins_jobs`.`jenkins_setting_id` AS t1_r3, `jenkins_jobs`.`name` AS t1_r4, `jenkins_jobs`.`latest_build_number` AS t1_r5, `jenkins_jobs`.`latest_build_date` AS t1_r6, `jenkins_jobs`.`latest_build_duration` AS t1_r7, `jenkins_jobs`.`state` AS t1_r8, `jenkins_jobs`.`health_report` AS t1_r9, `jenkins_jobs`.`description` AS t1_r10, `jenkins_jobs`.`created_at` AS t1_r11, `jenkins_jobs`.`updated_at` AS t1_r12, `projects`.`id` AS t2_r0, `projects`.`name` AS t2_r1, `projects`.`description` AS t2_r2, `projects`.`homepage` AS t2_r3, `projects`.`is_public` AS t2_r4, `projects`.`parent_id` AS t2_r5, `projects`.`created_on` AS t2_r6, `projects`.`updated_on` AS t2_r7, `projects`.`identifier` AS t2_r8, `projects`.`status` AS t2_r9, `projects`.`lft` AS t2_r10, `projects`.`rgt` AS t2_r11, `projects`.`inherit_members` AS t2_r12 FROM `jenkins_builds` LEFT OUTER JOIN `jenkins_jobs` ON `jenkins_jobs`.`id` = `jenkins_builds`.`jenkins_job_id` LEFT OUTER JOIN `projects` ON `projects`.`id` = `jenkins_jobs`.`project_id` WHERE (jenkins_builds.author_id = 4) AND (projects.status = 1 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='jenkins')) ORDER BY jenkins_builds.id DESC LIMIT 10):
  lib/plugins/acts_as_activity_provider/lib/acts_as_activity_provider.rb:82:in `find_events'
  lib/redmine/activity/fetcher.rb:76:in `block (2 levels) in events'
  lib/redmine/activity/fetcher.rb:75:in `each'
  lib/redmine/activity/fetcher.rb:75:in `block in events'
  lib/redmine/activity/fetcher.rb:74:in `each'
  lib/redmine/activity/fetcher.rb:74:in `events'
  app/controllers/users_controller.rb:65:in `show'
```

**Comment by ppawlowski** [comment]
I have exactly same error. Redmine version: 2.4.5 .
Table jenkins_builds has following schema:

| id             | int(11)      | NO   | PRI | NULL    | auto_increment |
| jenkins_job_id | int(11)      | NO   |     | NULL    |                |
| number         | int(11)      | NO   |     | NULL    |                |
| result         | varchar(255) | YES  |     | NULL    |                |
| finished_at    | datetime     | YES  |     | NULL    |                |
| building       | tinyint(1)   | YES  |     | NULL    |                |
| duration       | int(11)      | YES  |     | NULL    |                |

Bug causes, that Redmine with this plugin is useless.

**Comment by tchemineau** [comment]
Same error with redmine 2.5.1.stable.

**Comment by tchemineau** [comment]
I add the author_id column to prevent crashes, into `db/migrate/003_create_jenkins_builds.rb` :

```
class CreateJenkinsBuilds < ActiveRecord::Migration

  def self.up
    create_table :jenkins_builds do |t|
      t.column :jenkins_job_id, :integer, :null => false
      t.column :number,         :integer, :null => false
      t.column :author_id,      :integer
      t.column :result,         :string
      t.column :finished_at,    :datetime
      t.column :building,       :boolean
      t.column :duration,       :integer
    end
  end

  def self.down
    drop_table :jenkins_builds
  end

end
```

It seems that this workaround works.

**Comment by n-rodriguez** [comment]
Hi there!
Fixed in commit https://github.com/jbox-web/redmine_jenkins/commit/0d304824f682df2baf9aa5e0f115e70d200d7436.
