### ISSUE TITLE
Plugin installs fine but project activity tab is broken

### ISSUE THREAD

**Issue by drvora** [jbox-web/redmine_jenkins#40]
We have a bitnami redmine 3.0.2 installed. We have installed plugin using following steps:

1) Download zip file

2) unzip in plugins directory

3) Run commands,
$ cd apps/redmine/htdocs
$ bundle install --without development test postgresql sqlite --no-deployment
$ bundle install --without development test postgresql sqlite --deployment
$ ruby bin/rake redmine:plugins RAILS_ENV=production

4) restart redmine.

It installs fine but when we create a project (with or without Jenkins module enabled) it breaks the activity tab of the project. And we get following error in production.log

```
Started GET "/redmine/projects/davetest/activity" for 172.24.91.200 at 2015-05-11 16:23:55 -0400
Processing by ActivitiesController#index as HTML
Parameters: {"id"=>"davetest"}
Current user: admin (id=1)
Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.4ms)
NameError (uninitialized constant JenkinsBuild):
lib/redmine/activity/fetcher.rb:106:in `map'
lib/redmine/activity/fetcher.rb:106:in `constantized_providers'
lib/redmine/activity/fetcher.rb:42:in `block in event_types'
lib/redmine/activity/fetcher.rb:40:in `select'
lib/redmine/activity/fetcher.rb:40:in `event_types'
lib/redmine/activity/fetcher.rb:30:in `initialize'
app/controllers/activities_controller.rb:37:in `new'
app/controllers/activities_controller.rb:37:in `index'
```

**Comment by drvora** [comment]
Is there any workaround for this problem? We can't seem to figure out what the cause is. Our users really want this plugin working for efficient development collaboration. Thanks in advance.

**Comment by nhansds** [comment]
@drvora @n-rodriguez Got the same problem. I've got an 404 error when i try to access the Jenkins tab.
The jenkins Tab = translation missing : fr.label_jenkins
I can't access to the activity anymore
