### ISSUE TITLE
Installation fail in Bitnami Redmine stack

### ISSUE THREAD

**Issue by aalmada** [jbox-web/redmine_jenkins#43]
I followed the installation steps but the last step keeps failing. Can't figure out why.

There was an issue with Nokogiri but the following command fixed it: sudo apt-get install zlib1g-dev

I'm getting the following trace:

```
bitnami@linux:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins$ rake --trace redmine:plugins:migrate RAILS_ENV=production
(in /opt/bitnami/apps/redmine/htdocs)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: No such file to load -- will_paginate/view_helpers/action_view
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_bootstrap_kit/app/helpers/bootstrap/will_paginate_helper.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_bootstrap_kit/app/helpers/bootstrap_helper.rb:10:in `<module:BootstrapHelper>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_bootstrap_kit/app/helpers/bootstrap_helper.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_bootstrap_kit/app/helpers/redmine_bootstrap_kit_helper.rb:5:in `<module:RedmineBootstrapKitHelper>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_bootstrap_kit/app/helpers/redmine_bootstrap_kit_helper.rb:1:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:317:in `depend_on'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:233:in `require_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:149:in `block in modules_for_helpers'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `map!'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:108:in `helper'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:13:in `block in included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `class_eval'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:9:in `included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `include'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins/patches/projects_controller_patch.rb:40:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:317:in `depend_on'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:233:in `require_dependency'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins.rb:11:in `block (2 levels) in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/lib/redmine_jenkins.rb:9:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `block in simple'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `block in call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_prepare_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by aalmada** [comment]
Tried some more things but still getting this:

```
bitnami@linux:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins$ bundle exec rake --trace redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting
(in /opt/bitnami/apps/redmine/htdocs)
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x007f41bba28790>
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/railtie/configuration.rb:95:in `method_missing'
/opt/bitnami/apps/redmine/htdocs/config/application.rb:20:in `<class:Application>'
/opt/bitnami/apps/redmine/htdocs/config/application.rb:8:in `<module:RedmineApp>'
/opt/bitnami/apps/redmine/htdocs/config/application.rb:7:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:5:in `require'
/opt/bitnami/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/bin/rake:23:in `load'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins/vendor/bundle/ruby/2.0.0/bin/rake:23:in `<main>'
```

**Comment by n-rodriguez** [comment]
> LoadError: No such file to load -- will_paginate/view_helpers/action_view

What does `bundle list` say? Does it containt will_paginate gem?

**Comment by aalmada** [comment]
I forgot to mention I'm using Redmine 3.0.3 and I now noticed that there are already [reported issues on redmine_bootstrap_kit related to the latest Redmine versions](https://github.com/jbox-web/redmine_bootstrap_kit/issues). Although I didn't have any problem installing redmine_bootstrap_kit.

**'bundle list' returns the following:**

Gems included by the bundle:
- actionmailer (4.2.1)
- actionpack (4.2.1)
- actionpack-action_caching (1.1.1)
- actionpack-xml_parser (1.0.1)
- actionview (4.2.1)
- activejob (4.2.1)
- activemodel (4.2.1)
- activerecord (4.2.1)
- activesupport (4.2.1)
- arel (6.0.0)
- builder (3.2.2)
- bundler (1.10.5)
- coderay (1.1.0)
- erubis (2.7.0)
- globalid (0.3.5)
- hike (1.2.3)
- i18n (0.7.0)
- jquery-rails (3.1.2)
- json (1.8.2)
- loofah (2.0.1)
- mail (2.6.3)
- mime-types (2.5)
- mini_portile (0.6.2)
- minitest (5.6.0)
- multi_json (1.11.0)
- mysql2 (0.3.14)
- net-ldap (0.3.1)
- nokogiri (1.6.6.2)
- protected_attributes (1.0.9)
- rack (1.6.0)
- rack-openid (1.4.2)
- rack-test (0.6.3)
- rails (4.2.1)
- rails-deprecated_sanitizer (1.0.3)
- rails-dom-testing (1.0.6)
- rails-html-sanitizer (1.0.2)
- railties (4.2.1)
- rake (10.4.2)
- rbpdf (1.18.5)
- redcarpet (3.1.2)
- request_store (1.0.5)
- rmagick (2.13.4)
- ruby-openid (2.3.0)
- sprockets (2.12.3)
- sprockets-rails (2.2.4)
- thor (0.19.1)
- thread_safe (0.3.5)
- tilt (1.4.1)
- tzinfo (1.2.2)

**And 'gem list' returns the following:**

**\* LOCAL GEMS ***

actionmailer (4.2.3, 4.2.0)
actionpack (4.2.3, 4.2.0)
actionview (4.2.3, 4.2.0)
activejob (4.2.3, 4.2.0)
activemodel (4.2.3, 4.2.0)
activerecord (4.2.3, 4.2.0)
activesupport (4.2.3, 4.2.0)
akami (1.2.0)
arel (6.0.0)
atomic (1.1.14)
aws-sdk (1.8.3.1)
bcrypt-ruby (3.1.1)
bigdecimal (1.2.0)
binding_of_caller (0.7.2)
bluecloth (2.2.0)
builder (3.2.2, 3.1.4)
bundler (1.10.5, 1.9.6)
byebug (3.5.1)
charlock_holmes (0.6.9.4)
coffee-rails (4.1.0)
coffee-script (2.2.0)
coffee-script-source (1.6.2)
columnize (0.9.0)
crack (0.3.1)
daemon_controller (1.2.0)
daemons (1.1.8)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
diff-lcs (1.1.3)
erubis (2.7.0)
escape_utils (0.2.4)
eventmachine (1.0.4)
execjs (1.4.0)
faraday (0.8.4)
faraday_middleware (0.9.0)
fast_stack (0.1.0)
fast_xor (1.1.1)
fast_xs (0.8.0)
ffi (1.9.0)
gherkin (2.11.1)
github-markdown (0.5.3)
globalid (0.3.0)
gyoku (0.4.6)
haml (4.0.6)
haml-rails (0.9.0)
hashie (1.2.0)
hike (1.2.3)
hiredis (0.4.5)
hoe (3.0.6)
hoe-bundler (1.2.0)
hoe-debugging (1.0.5)
hoe-gemspec (1.0.0)
html2haml (2.0.0)
http_parser.rb (0.5.3)
httparty (0.8.3)
httpauth (0.2.0)
i18n (0.7.0)
iconv (1.0.3)
io-console (0.4.2)
jbuilder (2.0.7)
jenkins_api_client (1.3.0)
jquery-rails (3.0.4)
json (1.8.3, 1.8.1, 1.7.7)
jwt (0.1.8)
libv8 (3.16.14.3 x86_64-linux)
loofah (2.0.2, 2.0.1)
mail (2.5.4)
memcache-client (1.8.5)
mime-types (1.23)
mini_magick (3.4)
mini_portile (0.6.2, 0.6.0)
minitest (5.7.0, 5.3.3, 4.3.2, 3.3.0)
mixlib-shellout (2.1.0)
multi_json (1.5.0, 1.3.6)
multi_xml (0.5.1)
multipart-post (1.1.5)
mysql2 (0.3.14)
nokogiri (1.6.6.2, 1.6.2.1, 1.5.9)
oauth (0.4.7)
oj (2.0.11)
omniauth (1.1.4)
passenger (5.0.6)
pg (0.18.0.pre20141117110243, 0.15.1)
polyglot (0.3.3)
posix-spawn (0.3.6)
psych (2.0.0)
racc (1.4.8)
rack (1.6.4, 1.6.0)
rack-test (0.6.3, 0.6.2)
rails (4.2.3, 4.2.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6, 1.0.5)
rails-html-sanitizer (1.0.2, 1.0.1)
railties (4.2.3, 4.2.0)
rake (10.4.2, 10.1.0, 0.9.6, 0.8.7)
rake-compiler (0.8.1)
rdiscount (1.6.8)
rdoc (4.0.0)
redcarpet (3.0.0, 2.2.2)
RedCloth (4.2.9)
redis (3.0.4)
ref (1.0.2)
rexical (1.0.5)
rinku (1.7.3)
rmagick (2.13.1)
rspec (2.11.0)
rspec-core (2.11.1)
rspec-expectations (2.11.2)
rspec-mocks (2.11.1)
ruby-hmac (0.4.0)
ruby_parser (3.7.0)
rvm (1.11.3.5)
sass (3.2.9)
sass-rails (5.0.1)
sdoc (0.4.0)
sexp_processor (4.6.0)
simple_oauth (0.1.9)
slop (3.6.0)
spring (1.2.0)
sprockets (2.10.0, 2.2.1)
sprockets-rails (2.0.1)
sqlite3 (1.3.10)
sqlite3-ruby (1.3.3)
subexec (0.2.2)
terminal-table (1.5.1)
test-unit (2.0.0.0)
therubyracer (0.12.0)
thin (1.5.1)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5, 0.3.4)
tilt (2.0.1, 1.4.1)
treetop (1.4.14)
turbolinks (1.2.0)
twitter-stream (0.1.16)
tzinfo (1.2.2, 1.1.0)
tzinfo-data (1.2014.2)
uglifier (2.1.1)
uuidtools (2.1.3)
web-console (2.0.0)
will_paginate (3.0.7)
yajl-ruby (1.1.0)

**Comment by sixdrum** [comment]
I'm seeing the same issue with Ruby 2.2.2 on CentOS 6.6 x86_64 with Redmine 3.1.

**Comment by n-rodriguez** [comment]
> I'm seeing the same issue with Ruby 2.2.2 on CentOS 6.6 x86_64 with Redmine 3.1.

On Bitnami stack?

**Comment by n-rodriguez** [comment]
> bitnami@linux:/opt/bitnami/apps/redmine/htdocs/plugins/redmine_jenkins$ bundle exec rake --trace redmine:plugins:migrate RAILS_ENV=production NAME=redmine_git_hosting

The command `bundle exec rake...` must be executed from Redmine **root** directory. (`/opt/bitnami/apps/redmine/htdocs`)
