### ISSUE TITLE
500 Internal Server Error when edit settings.

### ISSUE THREAD

**Issue by slapt** [jbox-web/redmine_jenkins#7]
Hello.

When I go to any Project -> Modify settings for enable Jenkins plugin, I got this error:

Rendered projects/settings.html.erb within layouts/base (514.7ms)
Completed 500 Internal Server Error in 533.5ms

```
ActionView::Template::Error (undefined local variable or method `impasse_custom_fields_tabs' for #<#<Class:0x002ada352a9f10>:0x002ada3703fca0>):
   5: </div>
   6: <% unless @custom_fields_by_type.empty? %>
   7:   <fieldset class="box" id="impasse_custom_fields"><legend><%=l(:label_custom_field_plural)%></legend>
   8:     <% impasse_custom_fields_tabs.each do |tab| %>
   9:       <% if @custom_fields_by_type[tab[:name]] %>
   10:         <h3><%= l(tab[:label])%></h3>
   11:         <div>
  app/helpers/application_helper.rb:1043:in `labelled_form_for'
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__3559142713543177527_23558357021540'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__3559142713543177527_23558357021540'
  app/helpers/application_helper.rb:318:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__2258813952553908635_23558357099020'
```

P. S.: I have a full admin permissions.

**Comment by ChrisWesterfield** [comment]
I git this to.
But it seems to be related to my jenkins update to 1.577

does any one else expierence that to?

**Comment by n-rodriguez** [comment]
Hi there!

I've some tests with Jenkins 1.579 and it works pretty well.
I don't this is plugin related. The error is :

```
undefined local variable or method `impasse_custom_fields_tabs'
```

I think this comes from another plugin or from Redmine custom fields.
